#!/usr/bin/bash
MAKEFILE_DIR=./../..
cp $MAKEFILE_DIR/Makefile .
make $1 $2 SRCSDIR=$(pwd) HDRSDIR=$(pwd) EXTRA_LFLAGS="-lsfml-graphics -lsfml-window -lsfml-system" SELF="$MAKEFILE_DIR/Makefile"
rm -f Makefile